wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.19
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.12
    start_time: 1656304671
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 1
      - 16
      - 17
      4: 3.9.12
      5: 0.12.19
      8:
      - 5
      10:
      - 3
architecture:
  desc: null
  value: Sequential NN
batch_size:
  desc: null
  value: 256
epochs:
  desc: null
  value: 50
learning_rate:
  desc: null
  value: 0.0005
